import type { CampaignAngle, VideoVariantPreview } from "@/types/site";

export const campaignAngles: CampaignAngle[] = [
  {
    title: "Einstieg",
    angle: "Schnell ins erste Review",
    hooks: [
      "72 Stunden vom Briefing zum ersten Setup",
      "Weniger Koordination bis zur ersten sichtbaren Variante",
      "Aus einer Anfrage werden direkt belastbare Review-Routen",
    ],
    lengths: ["12s", "20s", "30s"],
  },
  {
    title: "Setup",
    angle: "Passende Rollen für die Anfrage",
    hooks: [
      "Zynapse kuratiert das Setup statt offener Freelancer-Suche",
      "Die richtigen Spezialist:innen pro Kampagne statt Vollzeit-Hiring",
      "Klare Verantwortlichkeiten statt offener Schleifen",
    ],
    lengths: ["15s", "25s", "35s"],
  },
  {
    title: "Varianten",
    angle: "Mehr Richtungen aus einem abgestimmten Setup",
    hooks: [
      "Mehr kreative Wege aus einem abgestimmten Setup",
      "Varianten ohne neue Sourcing-Schleife",
      "Mehr Auswahl für Review, Paid Social und nächste Ausspielungen",
    ],
    lengths: ["9s", "18s", "27s"],
  },
];

export const videoVariants: VideoVariantPreview[] = [
  {
    id: "v1",
    angle: "Produktlaunch",
    hookTitle: "Neues Produkt in wenigen Sekunden verständlich machen",
    format: "9:16",
    length: "12s",
    objective: "Erstkontakt",
    deliveryLabel: "Launch-Variante",
  },
  {
    id: "v2",
    angle: "Produktlaunch",
    hookTitle: "Vom ersten Scroll zur klaren Kernbotschaft",
    format: "1:1",
    length: "20s",
    objective: "Nutzenversprechen",
    deliveryLabel: "Paid Social",
  },
  {
    id: "v3",
    angle: "Produktverständnis",
    hookTitle: "Das Produkt im Einsatz statt nur im Claim zeigen",
    format: "4:5",
    length: "30s",
    objective: "Produktverständnis",
    deliveryLabel: "Anwendungsbild",
  },
  {
    id: "v4",
    angle: "Produktverständnis",
    hookTitle: "Von Problem zu Lösung in einem klaren Ablauf",
    format: "9:16",
    length: "15s",
    objective: "Problem-Lösung",
    deliveryLabel: "Erklär-Variante",
  },
  {
    id: "v5",
    angle: "Angebot & Entscheidung",
    hookTitle: "Angebot und Nutzen so zeigen, dass die Entscheidung leichter wird",
    format: "1:1",
    length: "25s",
    objective: "Angebotsfokus",
    deliveryLabel: "Entscheidungs-Variante",
  },
  {
    id: "v6",
    angle: "Angebot & Entscheidung",
    hookTitle: "Vertrauen vor dem Klick sichtbar machen",
    format: "4:5",
    length: "35s",
    objective: "Vertrauen",
    deliveryLabel: "Vertrauens-Variante",
  },
  {
    id: "v7",
    angle: "Nächste Ausspielung",
    hookTitle: "Aus Erstkontakt wird der nächste Entscheidungsschritt",
    format: "9:16",
    length: "9s",
    objective: "Weiterführung",
    deliveryLabel: "Nächste Runde",
  },
  {
    id: "v8",
    angle: "Nächste Ausspielung",
    hookTitle: "Ein stärkeres Argument für die zweite Ausspielung",
    format: "1:1",
    length: "18s",
    objective: "Vertiefung",
    deliveryLabel: "Folge-Variante",
  },
  {
    id: "v9",
    angle: "Nächste Ausspielung",
    hookTitle: "Mehr Lernsignale für die nächste Runde statt nur mehr Volumen",
    format: "4:5",
    length: "27s",
    objective: "Iteration",
    deliveryLabel: "Test-Variante",
  },
  {
    id: "v10",
    angle: "Handover & Skalierung",
    hookTitle: "Freigegebene Varianten direkt in den nächsten Kanal mitnehmen",
    format: "9:16",
    length: "14s",
    objective: "Skalierung",
    deliveryLabel: "Handover",
  },
  {
    id: "v11",
    angle: "Handover & Skalierung",
    hookTitle: "Ein Export, der Media, Content und Review zusammenhält",
    format: "1:1",
    length: "22s",
    objective: "Übergabe",
    deliveryLabel: "Asset-Paket",
  },
  {
    id: "v12",
    angle: "Handover & Skalierung",
    hookTitle: "Das Setup trägt auch die nächste Runde mit",
    format: "4:5",
    length: "32s",
    objective: "Nächste Runde",
    deliveryLabel: "Weiterführung",
  },
];

export const studioTimeline = [
  {
    title: "Eingabe",
    detail: "Ziel, Produkt, Guardrails, Budget, Kanal",
  },
  {
    title: "Setup",
    detail: "Rollen, Hooks, CTA-Routen, Freigaben, Produktionsplan",
  },
  {
    title: "Handover",
    detail: "Varianten, Versionen und Kontext für Review, Ads und nächste Iterationen",
  },
];
