import type { SeedTemplate } from "@/lib/workspace/seeds/types";

export const d2cProductLaunchTemplate: SeedTemplate = {
  key: "d2c_product_launch",
  label: "D2C product launch",
  campaignName: "Daily Glow Serum Launch Sprint",
  campaignGoal: "Launch-ready paid social creative for a new hero serum.",
  packageTier: "starter",
  currentStage: "in_review",
  stageDefinitions: [
    { key: "brief_received", status: "completed" },
    { key: "setup_planned", status: "completed" },
    { key: "production_ready", status: "completed" },
    { key: "in_review", status: "in_progress" },
    { key: "approved", status: "pending" },
    { key: "handover_ready", status: "pending" },
  ],
  brandProfile: {
    offerSummary: "A D2C skincare launch centered on glow, texture, and ingredient proof.",
    targetAudience: "Women 25-40 with an existing skincare routine and high creative fatigue.",
    primaryChannels: "Meta Reels, paid social landing videos, TikTok Spark Ads",
    brandTone: "Clean, premium, credible, but performance-aware",
    reviewNotes: "Keep product proof concrete, avoid broad beauty superlatives, and maintain fast mobile readability.",
    claimGuardrails: "No medical or cure claims. Avoid promising visible results in under 24 hours.",
  },
  preparedBlocks: {
    prepared: "One launch campaign, six launch-ready variants, and a review path already staged for your team.",
    review: "Your team can compare hook angles, proof moments, and CTA framing without needing a live sales walkthrough.",
    output: "The seeded output mirrors what Zynapse would hand over after the first review cycle: ready-to-export paid social variants.",
    nextStep: "If this launch logic fits, the next step is tightening approvals and finalizing the starter pilot scope.",
  },
  nextAction: {
    title: "Review the strongest proof-led launch angle",
    body: "Two variants already look close to approval. The remaining open thread is mainly about claim precision and CTA tightness.",
  },
  assets: [
    {
      key: "launch-hook-proof",
      title: "Hook 01 · Ingredient-first proof cut",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 22,
      versionLabel: "v3",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/d2c-product-launch/hook-01-proof.mp4",
      thumbnailPath: "demo-assets/d2c-product-launch/hook-01-proof.jpg",
    },
    {
      key: "launch-hook-texture",
      title: "Hook 02 · Texture reveal opener",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 18,
      versionLabel: "v2",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/d2c-product-launch/hook-02-texture.mp4",
      thumbnailPath: "demo-assets/d2c-product-launch/hook-02-texture.jpg",
    },
    {
      key: "launch-hook-routine",
      title: "Hook 03 · AM routine integration",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 20,
      versionLabel: "v2",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/d2c-product-launch/hook-03-routine.mp4",
      thumbnailPath: "demo-assets/d2c-product-launch/hook-03-routine.jpg",
    },
    {
      key: "launch-static-ugc",
      title: "Static 01 · Founder quote card",
      assetType: "static",
      format: "4:5",
      versionLabel: "v1",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/d2c-product-launch/static-01-founder-card.png",
      thumbnailPath: "demo-assets/d2c-product-launch/static-01-founder-card.jpg",
    },
    {
      key: "launch-static-benefits",
      title: "Static 02 · Benefits stack",
      assetType: "static",
      format: "4:5",
      versionLabel: "v2",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/d2c-product-launch/static-02-benefits.png",
      thumbnailPath: "demo-assets/d2c-product-launch/static-02-benefits.jpg",
    },
    {
      key: "launch-cutdown-reminder",
      title: "Cutdown · Retargeting reminder",
      assetType: "short_video",
      format: "1:1",
      durationSeconds: 12,
      versionLabel: "v1",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/d2c-product-launch/cutdown-retargeting.mp4",
      thumbnailPath: "demo-assets/d2c-product-launch/cutdown-retargeting.jpg",
    },
  ],
  reviewThreads: [
    {
      assetKey: "launch-hook-texture",
      createdBy: "brand_reviewer",
      anchorJson: "{\"timecode\":\"00:04\",\"focus\":\"opening claim\"}",
      comments: [
        {
          authorId: "brand_reviewer",
          body: "The opening line is directionally right, but it still sounds too much like a promise. We should keep it closer to texture proof.",
          commentType: "change_request",
        },
        {
          authorId: "zynapse_ops",
          body: "Noted. We can reframe it around product feel and ingredient context without implying guaranteed outcome.",
          commentType: "comment",
        },
      ],
    },
    {
      assetKey: "launch-hook-proof",
      createdBy: "brand_admin",
      anchorJson: "{\"timecode\":\"00:11\",\"focus\":\"cta framing\"}",
      comments: [
        {
          authorId: "brand_admin",
          body: "This one feels ready. The proof sequence lands and the CTA is clean enough for a first paid test.",
          commentType: "approval_note",
        },
      ],
    },
  ],
};
