import type { SeedTemplate } from "@/lib/workspace/seeds/types";

export const performanceRefreshTemplate: SeedTemplate = {
  key: "performance_refresh",
  label: "Kreative Auffrischung für bestehende Anzeigenmotive",
  campaignName: "Quartals-Auffrischung · Kernangebot neu testen",
  campaignGoal: "Abgenutzte Paid-Social-Motive erneuern, ohne das zugrunde liegende Angebot zu verändern.",
  packageTier: "growth",
  currentStage: "approved",
  stageDefinitions: [
    { key: "brief_received", status: "completed" },
    { key: "setup_planned", status: "completed" },
    { key: "production_ready", status: "completed" },
    { key: "in_review", status: "completed" },
    { key: "approved", status: "in_progress" },
    { key: "handover_ready", status: "pending" },
  ],
  brandProfile: {
    offerSummary: "Ein etabliertes Consumer-Produkt mit stabilem CAC, aber sinkender Reaktion auf die aktuellen Motive.",
    targetAudience: "Wiederkehrende Käuferinnen mit hoher Kaufabsicht und Lookalikes, die auf die bisherigen Leitmotive kaum noch reagieren.",
    primaryChannels: "Bezahlte Social-Ausspielung auf Meta, TikTok-Kurzfassungen und Hero-Schleifen auf der Landingpage",
    brandTone: "Klar in der Performance-Ansprache, mit leichtem Lifestyle-Finish",
    reviewNotes: "Starke Wirkbeweise schützen und gleichzeitig den Einstieg spürbar frischer wirken lassen.",
    claimGuardrails: "Vorher/Nachher nur zurückhaltend andeuten und absolute Aussagen vermeiden.",
  },
  preparedBlocks: {
    prepared: "Der Bereich gruppiert die Auffrischung bereits nach Ansatz, Version und Freigabestatus, damit euer Team sofort sieht, wo das nächste Testfenster aufgeht.",
    review: "In der Freigabe geht es hier darum zu entscheiden, welcher überarbeitete Ansatz wieder Budget verdient und nicht darum, die Kampagne neu zu starten.",
    output: "Die vorbereiteten Varianten simulieren die Art kontrollierter kreativer Auffrischungen, die Zynapse für einen monatlichen Rhythmus bündeln würde.",
    nextStep: "Der klarste nächste Schritt ist, die besten freigegebenen Varianten in den nächsten Sprint zu übernehmen.",
  },
  nextAction: {
    title: "Entscheiden, welche freigegebenen Varianten in das nächste Budgetfenster gehen",
    body: "Der aktuelle Bereich deutet auf einen Wachstumsrhythmus hin, weil mehrere Iterationen bereits rund um ein bewährtes Angebot gebündelt sind.",
  },
  assets: [
    {
      key: "refresh-proof-angle",
      title: "Variante 01 · Retest mit klarem Wirkbeweis",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 20,
      versionLabel: "v4",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/refresh-01-proof.mp4",
      thumbnailPath: "demo-assets/performance-refresh/refresh-01-proof.jpg",
    },
    {
      key: "refresh-social-proof",
      title: "Variante 02 · Remix mit sozialem Beweis",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 17,
      versionLabel: "v3",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/refresh-02-social-proof.mp4",
      thumbnailPath: "demo-assets/performance-refresh/refresh-02-social-proof.jpg",
    },
    {
      key: "refresh-ugc-style",
      title: "Variante 03 · Einstieg mit UGC-Anmutung",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 21,
      versionLabel: "v3",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/refresh-03-ugc.mp4",
      thumbnailPath: "demo-assets/performance-refresh/refresh-03-ugc.jpg",
    },
    {
      key: "refresh-square-proof",
      title: "Quadrat 01 · Wirkbeweis fürs Karussell",
      assetType: "static",
      format: "1:1",
      versionLabel: "v2",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/square-01-proof.png",
      thumbnailPath: "demo-assets/performance-refresh/square-01-proof.jpg",
    },
    {
      key: "refresh-square-comparison",
      title: "Quadrat 02 · Vergleichskarte",
      assetType: "static",
      format: "1:1",
      versionLabel: "v1",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/square-02-comparison.png",
      thumbnailPath: "demo-assets/performance-refresh/square-02-comparison.jpg",
    },
    {
      key: "refresh-cutdown",
      title: "Kurzfassung · Schleife für die Wiederansprache mit Wirkbeweis",
      assetType: "short_video",
      format: "4:5",
      durationSeconds: 14,
      versionLabel: "v2",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/cutdown-proof-loop.mp4",
      thumbnailPath: "demo-assets/performance-refresh/cutdown-proof-loop.jpg",
    },
  ],
  reviewThreads: [
    {
      assetKey: "refresh-ugc-style",
      createdBy: "brand_reviewer",
      anchorJson: "{\"timecode\":\"00:02\",\"focus\":\"opening energy\"}",
      comments: [
        {
          authorId: "brand_reviewer",
          body: "Die Richtung ist grundsätzlich brauchbar, aber der Einstieg wirkt im Vergleich zum bisherigen Gewinner noch zu generisch. Es braucht einen klareren Wirkbeweis gleich am Anfang.",
          commentType: "change_request",
        },
        {
          authorId: "zynapse_ops",
          body: "Wir können die ersten beiden Beats schärfen und den sozialen Beweis weiter unten im Frame halten. Dann hebt sich der Retest sauberer ab.",
          commentType: "comment",
        },
      ],
    },
    {
      assetKey: "refresh-social-proof",
      createdBy: "brand_admin",
      anchorJson: "{\"timecode\":\"00:09\",\"focus\":\"testimonial sequence\"}",
      comments: [
        {
          authorId: "brand_admin",
          body: "Diese Version ist stark genug für die nächste Ausspielung. Sie hält das Kernangebot zusammen und fühlt sich trotzdem deutlich frischer an.",
          commentType: "approval_note",
        },
      ],
    },
  ],
};
