import type { SeedTemplate } from "@/lib/workspace/seeds/types";

export const performanceRefreshTemplate: SeedTemplate = {
  key: "performance_refresh",
  label: "Performance creative refresh",
  campaignName: "Quarterly Creative Refresh · Core Offer Retest",
  campaignGoal: "Refresh fatigued paid social creatives without changing the underlying offer.",
  packageTier: "growth",
  currentStage: "approved",
  stageDefinitions: [
    { key: "brief_received", status: "completed" },
    { key: "setup_planned", status: "completed" },
    { key: "production_ready", status: "completed" },
    { key: "in_review", status: "completed" },
    { key: "approved", status: "in_progress" },
    { key: "handover_ready", status: "pending" },
  ],
  brandProfile: {
    offerSummary: "An established consumer product with stable CAC but declining creative response.",
    targetAudience: "Returning high-intent shoppers and lookalike audiences fatigued by the current hero variants.",
    primaryChannels: "Meta paid social, TikTok cutdowns, landing page hero loops",
    brandTone: "Direct response clarity with lighter lifestyle polish",
    reviewNotes: "Protect winning proof points while making the hook feel materially newer.",
    claimGuardrails: "Keep before/after implications subtle and avoid absolute statements.",
  },
  preparedBlocks: {
    prepared: "The workspace already groups the refresh by angle, version, and approval status so your team sees where the next test window opens.",
    review: "Review here is about deciding which refreshed angle is worth pushing back into spend, not restarting the campaign from zero.",
    output: "The seeded deliverables simulate the kind of controlled creative refresh Zynapse would package for a monthly rhythm.",
    nextStep: "The clearest next move is promoting the best approved variants into the next sprint scope.",
  },
  nextAction: {
    title: "Decide which approved refresh variants deserve the next spend window",
    body: "The current workspace suggests a Growth-style rhythm because multiple iterations are already clustered around one proven offer.",
  },
  assets: [
    {
      key: "refresh-proof-angle",
      title: "Refresh 01 · Proof-led retest",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 20,
      versionLabel: "v4",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/refresh-01-proof.mp4",
      thumbnailPath: "demo-assets/performance-refresh/refresh-01-proof.jpg",
    },
    {
      key: "refresh-social-proof",
      title: "Refresh 02 · Social proof remix",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 17,
      versionLabel: "v3",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/refresh-02-social-proof.mp4",
      thumbnailPath: "demo-assets/performance-refresh/refresh-02-social-proof.jpg",
    },
    {
      key: "refresh-ugc-style",
      title: "Refresh 03 · UGC-style open",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 21,
      versionLabel: "v3",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/refresh-03-ugc.mp4",
      thumbnailPath: "demo-assets/performance-refresh/refresh-03-ugc.jpg",
    },
    {
      key: "refresh-square-proof",
      title: "Square 01 · Carousel proof frame",
      assetType: "static",
      format: "1:1",
      versionLabel: "v2",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/square-01-proof.png",
      thumbnailPath: "demo-assets/performance-refresh/square-01-proof.jpg",
    },
    {
      key: "refresh-square-comparison",
      title: "Square 02 · Comparison card",
      assetType: "static",
      format: "1:1",
      versionLabel: "v1",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/square-02-comparison.png",
      thumbnailPath: "demo-assets/performance-refresh/square-02-comparison.jpg",
    },
    {
      key: "refresh-cutdown",
      title: "Cutdown · Retargeting proof loop",
      assetType: "short_video",
      format: "4:5",
      durationSeconds: 14,
      versionLabel: "v2",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/performance-refresh/cutdown-proof-loop.mp4",
      thumbnailPath: "demo-assets/performance-refresh/cutdown-proof-loop.jpg",
    },
  ],
  reviewThreads: [
    {
      assetKey: "refresh-ugc-style",
      createdBy: "brand_reviewer",
      anchorJson: "{\"timecode\":\"00:02\",\"focus\":\"opening energy\"}",
      comments: [
        {
          authorId: "brand_reviewer",
          body: "The idea is directionally useful, but the opening reads too generic compared to the existing winner. It needs a clearer proof beat.",
          commentType: "change_request",
        },
        {
          authorId: "zynapse_ops",
          body: "We can tighten the first two beats and keep the social proof lower in the frame. That should make the retest more distinct.",
          commentType: "comment",
        },
      ],
    },
    {
      assetKey: "refresh-social-proof",
      createdBy: "brand_admin",
      anchorJson: "{\"timecode\":\"00:09\",\"focus\":\"testimonial sequence\"}",
      comments: [
        {
          authorId: "brand_admin",
          body: "This version is strong enough to include in the next launch batch. It keeps the core offer but feels sufficiently refreshed.",
          commentType: "approval_note",
        },
      ],
    },
  ],
};
