import type { SeedTemplate } from "@/lib/workspace/seeds/types";

export const reviewSprintTemplate: SeedTemplate = {
  key: "review_sprint",
  label: "Multi-stakeholder brand review sprint",
  campaignName: "Stakeholder Review Sprint · Spring Narrative Alignment",
  campaignGoal: "Align a multi-stakeholder team around one review-ready creative route without operational chaos.",
  packageTier: "starter",
  currentStage: "in_review",
  stageDefinitions: [
    { key: "brief_received", status: "completed" },
    { key: "setup_planned", status: "completed" },
    { key: "production_ready", status: "completed" },
    { key: "in_review", status: "in_progress" },
    { key: "approved", status: "pending" },
    { key: "handover_ready", status: "pending" },
  ],
  brandProfile: {
    offerSummary: "A cross-functional review sprint for seasonal messaging where marketing, brand, and founder feedback all need to converge.",
    targetAudience: "Existing prospect audience segments already familiar with the product category but sensitive to narrative framing.",
    primaryChannels: "Meta video, paid social statics, internal stakeholder review rooms",
    brandTone: "Brand-led, confident, and operationally clean",
    reviewNotes: "The goal is less about volume and more about reducing approval chaos across multiple reviewers.",
    claimGuardrails: "Avoid overclaiming competitive superiority. Keep positioning language comparative but grounded.",
  },
  preparedBlocks: {
    prepared: "The workspace is already structured around one clear review sprint so multiple stakeholders can react without reopening the brief each time.",
    review: "Each open thread is tied to a specific asset and context note, making it easy to understand what still blocks approval.",
    output: "The seeded output shows what Zynapse would actually hand to a team that needs alignment, not just raw creative volume.",
    nextStep: "The next step is consolidating the open review notes into one approval-ready route instead of prolonging the sprint.",
  },
  nextAction: {
    title: "Consolidate open review notes into one approval-ready route",
    body: "The workspace already shows where stakeholder feedback overlaps and where a final approval decision is still blocked.",
  },
  assets: [
    {
      key: "review-hero-cut",
      title: "Hero Cut · Seasonal narrative opener",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 24,
      versionLabel: "v2",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/review-sprint/hero-cut.mp4",
      thumbnailPath: "demo-assets/review-sprint/hero-cut.jpg",
    },
    {
      key: "review-proof-cut",
      title: "Proof Cut · Benefits compression",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 19,
      versionLabel: "v3",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/review-sprint/proof-cut.mp4",
      thumbnailPath: "demo-assets/review-sprint/proof-cut.jpg",
    },
    {
      key: "review-founder-note",
      title: "Founder Note · Narrative rationale",
      assetType: "static",
      format: "4:5",
      versionLabel: "v1",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/review-sprint/founder-note.png",
      thumbnailPath: "demo-assets/review-sprint/founder-note.jpg",
    },
    {
      key: "review-comparison-card",
      title: "Comparison Card · Why this route now",
      assetType: "static",
      format: "1:1",
      versionLabel: "v2",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/review-sprint/comparison-card.png",
      thumbnailPath: "demo-assets/review-sprint/comparison-card.jpg",
    },
    {
      key: "review-ugc-remix",
      title: "UGC Remix · Voice-over variant",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 16,
      versionLabel: "v2",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/review-sprint/ugc-remix.mp4",
      thumbnailPath: "demo-assets/review-sprint/ugc-remix.jpg",
    },
    {
      key: "review-square-summary",
      title: "Summary Card · Internal approval snapshot",
      assetType: "static",
      format: "1:1",
      versionLabel: "v1",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/review-sprint/summary-card.png",
      thumbnailPath: "demo-assets/review-sprint/summary-card.jpg",
    },
  ],
  reviewThreads: [
    {
      assetKey: "review-hero-cut",
      createdBy: "brand_admin",
      anchorJson: "{\"timecode\":\"00:06\",\"focus\":\"brand framing\"}",
      comments: [
        {
          authorId: "brand_admin",
          body: "The opener feels close, but the brand framing should land slightly earlier so internal reviewers do not miss the strategic context.",
          commentType: "change_request",
        },
        {
          authorId: "brand_reviewer",
          body: "Agree on the timing. Once that line lands earlier, I think the rest of the cut is strong enough to move forward.",
          commentType: "comment",
        },
      ],
    },
    {
      assetKey: "review-proof-cut",
      createdBy: "brand_reviewer",
      anchorJson: "{\"timecode\":\"00:10\",\"focus\":\"benefit ordering\"}",
      comments: [
        {
          authorId: "brand_reviewer",
          body: "This one is likely the cleanest approval path. The benefit ordering already feels understandable without extra explanation.",
          commentType: "approval_note",
        },
      ],
    },
    {
      assetKey: "review-ugc-remix",
      createdBy: "zynapse_ops",
      anchorJson: "{\"timecode\":\"00:03\",\"focus\":\"opening voice-over\"}",
      comments: [
        {
          authorId: "zynapse_ops",
          body: "This is usable, but still a little too close to generic category language. We should push it further toward the agreed narrative route.",
          commentType: "change_request",
        },
      ],
    },
  ],
};
