import type { SeedTemplate } from "@/lib/workspace/seeds/types";

export const reviewSprintTemplate: SeedTemplate = {
  key: "review_sprint",
  label: "Freigabe-Sprint mit mehreren Entscheidungsträgern",
  campaignName: "Freigabesprint mit Entscheidungsträgern · Frühlingsnarrativ abstimmen",
  campaignGoal: "Ein Team mit mehreren Entscheidungsträgern auf eine freigabereife Kreativroute ausrichten, ohne operative Unruhe zu erzeugen.",
  packageTier: "starter",
  currentStage: "in_review",
  stageDefinitions: [
    { key: "brief_received", status: "completed" },
    { key: "setup_planned", status: "completed" },
    { key: "production_ready", status: "completed" },
    { key: "in_review", status: "in_progress" },
    { key: "approved", status: "pending" },
    { key: "handover_ready", status: "pending" },
  ],
  brandProfile: {
    offerSummary: "Ein bereichsübergreifender Freigabe-Sprint für saisonale Kommunikation, in dem Marketing, Marke und Feedback aus dem Gründerteam sauber zusammenlaufen müssen.",
    targetAudience: "Bestehende Zielgruppensegmente mit Verständnis für die Produktkategorie, die sensibel auf das richtige Narrativ reagieren.",
    primaryChannels: "Meta-Video, statische Paid-Social-Motive und interne Freigaberäume für Entscheidungsträger",
    brandTone: "Markengeführt, souverän und operativ klar",
    reviewNotes: "Das Ziel ist weniger Volumen als saubere Freigaben über mehrere Freigebende hinweg.",
    claimGuardrails: "Keine überzogenen Aussagen zur Überlegenheit. Positionierung vergleichend, aber belastbar formulieren.",
  },
  preparedBlocks: {
    prepared: "Der Bereich ist bereits um einen klaren Freigabe-Sprint strukturiert, damit mehrere Entscheidungsträger reagieren können, ohne das Briefing jedes Mal neu zu öffnen.",
    review: "Jede offene Diskussion ist an eine konkrete Variante und einen Kontext-Hinweis gebunden, sodass schnell klar wird, was die Freigabe noch blockiert.",
    output: "Das vorbereitete Paket zeigt, was Zynapse einem Team mit Abstimmungsbedarf tatsächlich übergeben würde und nicht nur rohe Kreativmasse.",
    nextStep: "Der nächste Schritt ist, die offenen Hinweise aus der Freigabe in eine freigabereife Richtung zu verdichten, statt den Sprint weiter in die Länge zu ziehen.",
  },
  nextAction: {
    title: "Offene Hinweise aus der Freigabe in eine freigabereife Richtung verdichten",
    body: "Der Bereich zeigt bereits, wo sich Feedback aus dem Entscheidungskreis überschneidet und wo die finale Freigabe noch blockiert ist.",
  },
  assets: [
    {
      key: "review-hero-cut",
      title: "Leitmotiv-Variante · Saisonaler Einstieg ins Narrativ",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 24,
      versionLabel: "v2",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/review-sprint/hero-cut.mp4",
      thumbnailPath: "demo-assets/review-sprint/hero-cut.jpg",
    },
    {
      key: "review-proof-cut",
      title: "Wirkbeweis-Variante · Verdichtete Nutzenargumentation",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 19,
      versionLabel: "v3",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/review-sprint/proof-cut.mp4",
      thumbnailPath: "demo-assets/review-sprint/proof-cut.jpg",
    },
    {
      key: "review-founder-note",
      title: "Hinweis aus dem Gründerteam · Einordnung des Narrativs",
      assetType: "static",
      format: "4:5",
      versionLabel: "v1",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/review-sprint/founder-note.png",
      thumbnailPath: "demo-assets/review-sprint/founder-note.jpg",
    },
    {
      key: "review-comparison-card",
      title: "Vergleichskarte · Warum diese Richtung jetzt trägt",
      assetType: "static",
      format: "1:1",
      versionLabel: "v2",
      reviewStatus: "approved",
      source: "seed",
      storagePath: "demo-assets/review-sprint/comparison-card.png",
      thumbnailPath: "demo-assets/review-sprint/comparison-card.jpg",
    },
    {
      key: "review-ugc-remix",
      title: "Remix aus nutzernaher Perspektive · Variante mit Sprechertext",
      assetType: "short_video",
      format: "9:16",
      durationSeconds: 16,
      versionLabel: "v2",
      reviewStatus: "changes_requested",
      source: "seed",
      storagePath: "demo-assets/review-sprint/ugc-remix.mp4",
      thumbnailPath: "demo-assets/review-sprint/ugc-remix.jpg",
    },
    {
      key: "review-square-summary",
      title: "Zusammenfassungskarte · Momentaufnahme für die interne Freigabe",
      assetType: "static",
      format: "1:1",
      versionLabel: "v1",
      reviewStatus: "pending",
      source: "seed",
      storagePath: "demo-assets/review-sprint/summary-card.png",
      thumbnailPath: "demo-assets/review-sprint/summary-card.jpg",
    },
  ],
  reviewThreads: [
    {
      assetKey: "review-hero-cut",
      createdBy: "brand_owner",
      anchorJson: "{\"timecode\":\"00:06\",\"focus\":\"brand framing\"}",
      comments: [
        {
          authorId: "brand_owner",
          body: "Der Einstieg ist nah dran, aber die Markenführung sollte etwas früher einsetzen, damit der strategische Kontext intern sofort klar ist.",
          commentType: "change_request",
        },
        {
          authorId: "brand_reviewer",
          body: "Sehe ich genauso. Wenn diese Zeile früher sitzt, ist der Rest des Cuts stark genug für den nächsten Schritt.",
          commentType: "comment",
        },
      ],
    },
    {
      assetKey: "review-proof-cut",
      createdBy: "brand_reviewer",
      anchorJson: "{\"timecode\":\"00:10\",\"focus\":\"benefit ordering\"}",
      comments: [
        {
          authorId: "brand_reviewer",
          body: "Das ist im Moment der sauberste Weg zur Freigabe. Die Reihenfolge der Nutzenargumente trägt schon ohne zusätzliche Erklärung.",
          commentType: "approval_note",
        },
      ],
    },
    {
      assetKey: "review-ugc-remix",
      createdBy: "ops",
      anchorJson: "{\"timecode\":\"00:03\",\"focus\":\"opening voice-over\"}",
      comments: [
        {
          authorId: "ops",
          body: "Das ist nutzbar, liegt sprachlich aber noch zu nah an generischer Kategorie-Kommunikation. Wir sollten es stärker auf die vereinbarte Narrativrichtung ziehen.",
          commentType: "change_request",
        },
      ],
    },
  ],
};
